version: "3"
services:

  db:
    image: postgres:14-alpine
    restart: always
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file: .env
    environment:
      XDEBUG_CONFIG: discover_client_host=true client_host=172.17.0.1 log_level=0
    volumes:
      - ./api:/app/api
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /app/api
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    env_file: .env
    environment:
      SOCK_PORT: 80
    volumes:
      - ./ui:/app/ui
    ports:
      - 3000:3000
    working_dir: /app/ui


  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    env_file: .env
    depends_on:
      - php
      - node
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/app/api
      - ./ui:/app/ui
    restart: always
    ports:
      - 80:80

  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    env_file: .env





volumes:
  db_data: