#-------


name: myCIActions

on: 
  push:
    branches: 
      - master
      
      
jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello WORDL"
  
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello WORDL DEPLOY JOB"
