#-------


name: myCIActions
env:
  APPLICATION_NAME: MyNameFruit
  PACKAGE_NAME: "CHTO_TO_TAM: ${{github.sha}}"

on: 
  push:
    branches: 
      - master
      
      
jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello WORDL"
        
      - name: Execute few commands
        run: |
          echo "Message ONE"
          echo "Message TWO"
          ls
          echo "Print THIS ${{env.APPLICATION_NAME}}"
  
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello WORDL DEPLOY JOB"
