#-------


name: myCIActions
env:
  APPLICATION_NAME: MyNameFruit
  PACKAGE_NAME: "CHTO_TO_TAM: ${{github.sha}}"

on:
  push:
    branches:
      - master


jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello WORDL"

      - name: Execute few commands
        run: |
          echo "Message ONE"
          echo "Message TWO"
          ls
          echo "Print THIS ${{env.APPLICATION_NAME}}"
      - name: Where am I 2
        run: ls -la


  my-deploy:
    runs-on: ubuntu-latest
    needs: [ my-testing ]
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SSH_HOST}} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.WORK_DIR}} && git checkout ${{secrets.MAIN_BRANCH}} && git pull && ./down.sh && ./buildup.sh && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
